### ISSUE TITLE
Comment on RFC009 (S3)

### ISSUE THREAD

**Issue by AtjonTV** [appwrite/rfc#15]
I suggest that RFC009 not only includes AWS S3 but all S3 servers (service agnostic).

I for example have my own S3 MinIO server as well as Scaleway S3 Object Storage.

From the RFC009 I can only see that AWS S3 would be available based on the limited configuration, so I cannot use my preferred server or service.

In my opinion generic S3 server support is the only long term solution when it comes to S3 support.

**Comment by eldadfux** [comment]
We also plan to support generic S3 servers once first implementation with AWS is completed.
