### ISSUE TITLE
RFC Aplication process is too hard...

### ISSUE THREAD

**Issue by sshyran** [appwrite/rfc#20]
Well... isn't it? I've just gone through Readme.... and it looks like I'm pressured/forced to do all the aplication processing work instead of RFC Repo maintainers... and it does not inspire to propose anything that way! 

Please, consider using Issues tab in this Appwrite RFC  repo as primary entry point for new issues and feature requests... that will drastically improve UX, and a good will to get easily involwed and be heard... thanks.

**Comment by eldadfux** [comment]
Hey @sshyran you don't have to write the RFC. Feel free to open an issue or discussion on the main Github repo with your idea. If accepted by the team, we can also write the RFC for it. The RFC is used as the final step before implementing new features, and we use it as our spec for actual implementation.

**Comment by christyjacob4** [comment]
Hey, @sshyran  Sorry if the information was misleading 😄 . The RFC process is the final step before the implementation of BIG features. You can get an idea of BIG by going through some of our already merged RFCs. 
Github issues continue to be the primary place for raising issues, bugs, and even feature requests :)

**Comment by sshyran** [comment]
okay...

**Comment by sshyran** [comment]
So,  if I get it well, this repo is for Maintainers,  then please.... explicitly specify it in Readme!

**Comment by sshyran** [comment]
When/if done - maintainers are welcome to close this issue...

**Comment by christyjacob4** [comment]
> So, if I get it well, this repo is for Maintainers, 

@sshyran  Absolutely not 😄  We haven't had any major feature proposal coming in from the community yet hence you see that the RFCs are from maintainers so far. But we definitely want to change that. 

Please let us know if there is a feature you'd like to see in Appwrite and we can decide between a Github issue or an RFC for it . Also if you feel you could help improve the README we would love a PR
